// This file is automatically generated. Do not modify.
// This file is used to store the Firebase configuration.
// It is used by the Firebase client and server providers.

// Replace this with your own Firebase configuration.
export const firebaseConfig = {
  apiKey: "AIzaSyDIF5AtjKxpLuqrP0ldLPcf3pJA_Gjpkzs",
  authDomain: "studio-5154768706-56b71.firebaseapp.com",
  projectId: "studio-5154768706-56b71",
  storageBucket: "studio-5154768706-56b71.appspot.com",
  messagingSenderId: "364659110802",
  appId: "1:364659110802:web:f35a1e9b32c5bdd6abc74b",
};
