// This file is automatically generated. Do not modify.
// This file is used to store the Firebase configuration.
// It is used by the Firebase client and server providers.

// Replace this with your own Firebase configuration.
export const firebaseConfig = {
  apiKey: "your-api-key",
  authDomain: "your-auth-domain",
  projectId: "your-project-id",
  storageBucket: "your-storage-bucket",
  messagingSenderId: "your-messaging-sender-id",
  appId: "your-app-id",
};
